In [2]:
#importing the dependecies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
#loading the dataset into the workspace
data = pd.read_csv('poddf.csv')
data.head()

index                            Name Rating_Volume   Rating       Genre  \
0      0                       Fresh Air         10188  4.46133        Arts   
1      1                        The Moth         10154  4.69982  Performing   
2      2                   99% Invisible         12303   4.8693      Design   
3      3  iFanboy.com Comic Book Podcast          1335  4.79551      Visual   
4      4               Myths and Legends         11128  4.88282  Literature   

                                         Description  
0  Fresh Air from WHYY, the Peabody Award-winning...  
1  Since its launch in 1997, The Moth has present...  
2  Design is everywhere in our lives, perhaps mos...  
3  The iFanboy.com Comic Book Podcast is a weekly...  
4  Jason Weiser tells stories from myths, legends...

In [4]:
podcast = data[['Name','Genre','Description']]
podcast.head()

Name       Genre  \
0                       Fresh Air        Arts   
1                        The Moth  Performing   
2                   99% Invisible      Design   
3  iFanboy.com Comic Book Podcast      Visual   
4               Myths and Legends  Literature   

                                         Description  
0  Fresh Air from WHYY, the Peabody Award-winning...  
1  Since its launch in 1997, The Moth has present...  
2  Design is everywhere in our lives, perhaps mos...  
3  The iFanboy.com Comic Book Podcast is a weekly...  
4  Jason Weiser tells stories from myths, legends...

In [5]:
podcast.shape

(13632, 3)

In [6]:
combine_features = data['Name'] + ' ' + data['Genre'] + ' ' + data['Description']

In [7]:
print(combine_features)

0        Fresh Air Arts Fresh Air from WHYY, the Peabod...
1        The Moth Performing Since its launch in 1997, ...
2        99% Invisible Design Design is everywhere in o...
3        iFanboy.com Comic Book Podcast Visual The iFan...
4        Myths and Legends Literature Jason Weiser tell...
                               ...                        
13627    Puromac Tech News Puromac es una conversación ...
13628    AVexcel Tech News AVexcel is your guide to the...
13629    Take a Network Break And Get The Latest Networ...
13630    AVexcel Tech News AVexcel is your guide to the...
13631    Take a Network Break And Get The Latest Networ...
Length: 13632, dtype: object


In [8]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combine_features)

In [9]:
similarity = cosine_similarity(feature_vectors)

In [10]:
print(similarity)

[[1.         0.03788201 0.06123121 ... 0.01265802 0.01258005 0.01265802]
 [0.03788201 1.         0.03762742 ... 0.04220054 0.01630242 0.04220054]
 [0.06123121 0.03762742 1.         ... 0.01621951 0.0209209  0.01621951]
 ...
 [0.01265802 0.04220054 0.01621951 ... 1.         0.08363158 1.        ]
 [0.01258005 0.01630242 0.0209209  ... 0.08363158 1.         0.08363158]
 [0.01265802 0.04220054 0.01621951 ... 1.         0.08363158 1.        ]]


In [11]:
import difflib
podcast_Name = str(input('Enter the name of your favorite podcast : '))
list_of_all_names = data['Name'].tolist()
find_close_match = difflib.get_close_matches(podcast_Name, list_of_all_names)
print(find_close_match)

['Millennial']


In [12]:
close_match = find_close_match[0]
print(close_match)

Millennial


In [13]:
index_of_the_podcast_name = data[data['Name'] == close_match]['index'].values[0]
print(index_of_the_podcast_name)

10541


In [14]:
similarity_score = list(enumerate(similarity[index_of_the_podcast_name]))

In [15]:
sorted_similar_podcast_name = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_podcast_name)

[(10541, 1.0), (49, 0.4642952142954985), (10482, 0.40726602902306785), (6281, 0.37702792574867794), (10425, 0.3549470229024744), (2, 0.336698052007208), (10409, 0.2718297588553482), (10451, 0.26111471318804425), (10379, 0.2572261757659939), (10538, 0.1998370931767356), (38, 0.19018376621543032), (2215, 0.1879251212441303), (5342, 0.18769558567215006), (1760, 0.17225281751915705), (9307, 0.15808043599441748), (3481, 0.15556086959110338), (329, 0.15153536151279026), (10935, 0.1486556859159286), (5572, 0.1274118434045588), (2343, 0.10969223815201702), (11811, 0.10953888279420455), (10808, 0.10325576643059647), (10941, 0.09959818861133654), (6986, 0.09584221105139243), (8695, 0.09471615969240715), (7780, 0.0944747297958304), (5484, 0.09400434005163269), (2339, 0.09378779024070759), (10806, 0.09243176526281788), (6844, 0.09207807039101447), (10565, 0.09160436540133823), (2211, 0.09153367726593843), (10851, 0.09046571764601716), (10861, 0.09019758822603034), (10929, 0.08998533220964923), (29

In [16]:
print('Podcast recommended for you : \n')

i = 1

for name in sorted_similar_podcast_name:
  index = name[0]
  title_from_index = data[data.index==index]['Name'].values[0]
  if (i<10):
    print(i, '.',title_from_index)
    i+=1

Podcast recommended for you : 

1 . Millennial
2 . The Allusionist
3 . Benjamen Walker's Theory of Everything
4 . The Heart
5 . The Mortified Podcast
6 . 99% Invisible
7 . Love + Radio
8 . Radio Diaries
9 . the memory palace


<h2 align='center'>| FINAL PODCAST RECOMMENDATION SYSTEM |</h2>

In [21]:
podcast_Name = input(' Enter your favourite podcast name : ')

list_of_all_names = data['Name'].tolist()

find_close_match = difflib.get_close_matches(podcast_Name, list_of_all_names)

close_match = find_close_match[0]

index_of_the_podcast_name = data[data.Name == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_podcast_name]))

sorted_similar_podcast_name = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Podcast recommended for you : \n')

i = 1

for movie in sorted_similar_podcast_name:
    index = movie[0]
    title_from_index = data[data.index==index]['Name'].values[0]
    if (i<30):
        print(i, '.',title_from_index)
        i+=1

Podcast recommended for you : 

1 . The Tim Ferriss Show
2 . Tribe of Mentors
3 . The Random Show Podcast
4 . TNT PODCAST
5 . Pro Tools Expert Podcast
6 . The Random Show Podcast: Audio
7 . Waking Up with Sam Harris
8 . The Kevin Rose Show
9 . Noah Kagan Presents
10 . Perpetual Chess Podcast
11 . Chess Is Cool Podcast with Alexandra Kosteniuk
12 . PE's Chess Cast
13 . Rich Dad Radio Show: In-Your-Face Advice on Investing, Personal Finance, & Starting a Business
14 . Outperform
15 . The Anxiety Podcast
16 . From Pixels to Print – a graphic design discussion
17 . SECRETS TO REAL ESTATE INVESTING SHOW | HOUSE FLIPPING | CASH FLOW | INVESTING | LANDLORD
18 . CMS Media Calls
19 . Chess Killer Tips Video Podcast with Alexandra Kosteniuk
20 . The Less Doing Podcast with Ari Meisel: The Best Life Hacks And Productivity Tips For Less Doing, More Living
21 . The Cashflow Academy Show
22 . Paul Merriman
23 . Real Estate Investing For Women
24 . Best Real Estate Investing Advice Ever with Joe Fair